<?php

namespace Database\Seeders;

use App\Models\Commune;
use App\Models\Province;
use App\Models\Region;
use Illuminate\Database\Seeder;

class LocaliteTableSeeder extends Seeder
{
    public function run()
    {
        $regions = ['Est', 'Centre', 'Centre-Ouest', 'Centre-Nord', 'Sahel', 'Plateau-Central', 'Nord', 'Hauts-Bassins', 'Sud-Ouest', 'Boucle du Mouhoun', 'Cascades', 'Centre-Est', 'Centre-Sud'];
        foreach ($regions as $key => $region) {
            Region::create([
                'libelle' => $region,
            ]);
        }

        $provinces = [
            ['libelle' => 'Balé', 'region_id' => Region::where('libelle', 'Boucle du Mouhoun')->first()->uuid],
            ['libelle' => 'Banwa', 'region_id' => Region::where('libelle', 'Boucle du Mouhoun')->first()->uuid],
            ['libelle' => 'Kossi', 'region_id' => Region::where('libelle', 'Boucle du Mouhoun')->first()->uuid],
            ['libelle' => 'Mouhoun', 'region_id' => Region::where('libelle', 'Boucle du Mouhoun')->first()->uuid],
            ['libelle' => 'Nayala', 'region_id' => Region::where('libelle', 'Boucle du Mouhoun')->first()->uuid],
            ['libelle' => 'Sourou', 'region_id' => Region::where('libelle', 'Boucle du Mouhoun')->first()->uuid],
            ['libelle' => 'Comoé', 'region_id' => Region::where('libelle', 'Cascades')->first()->uuid],
            ['libelle' => 'Léraba', 'region_id' => Region::where('libelle', 'Cascades')->first()->uuid],
            ['libelle' => 'Kadiogo', 'region_id' => Region::where('libelle', 'Centre')->first()->uuid],
            ['libelle' => 'Boulgou', 'region_id' => Region::where('libelle', 'Centre-Est')->first()->uuid],
            ['libelle' => 'Koulpélogo', 'region_id' => Region::where('libelle', 'Centre-Est')->first()->uuid],
            ['libelle' => 'Kouritenga', 'region_id' => Region::where('libelle', 'Centre-Est')->first()->uuid],
            ['libelle' => 'Bam', 'region_id' => Region::where('libelle', 'Centre-Nord')->first()->uuid],
            ['libelle' => 'Namentenga', 'region_id' => Region::where('libelle', 'Centre-Nord')->first()->uuid],
            ['libelle' => 'Sanmatenga', 'region_id' => Region::where('libelle', 'Centre-Nord')->first()->uuid],
            ['libelle' => 'Boulkiemdé', 'region_id' => Region::where('libelle', 'Centre-Ouest')->first()->uuid],
            ['libelle' => 'Sanguié', 'region_id' => Region::where('libelle', 'Centre-Ouest')->first()->uuid],
            ['libelle' => 'Sissili', 'region_id' => Region::where('libelle', 'Centre-Ouest')->first()->uuid],
            ['libelle' => 'Ziro', 'region_id' => Region::where('libelle', 'Centre-Ouest')->first()->uuid],
            ['libelle' => 'Bazèga', 'region_id' => Region::where('libelle', 'Centre-Sud')->first()->uuid],
            ['libelle' => 'Nahouri', 'region_id' => Region::where('libelle', 'Centre-Sud')->first()->uuid],
            ['libelle' => 'Zoundwéogo', 'region_id' => Region::where('libelle', 'Centre-Sud')->first()->uuid],
            ['libelle' => 'Gnagna', 'region_id' => Region::where('libelle', 'Est')->first()->uuid],
            ['libelle' => 'Gourma', 'region_id' => Region::where('libelle', 'Est')->first()->uuid],
            ['libelle' => 'Komondjari', 'region_id' => Region::where('libelle', 'Est')->first()->uuid],
            ['libelle' => 'Kompienga', 'region_id' => Region::where('libelle', 'Est')->first()->uuid],
            ['libelle' => 'Tapoa', 'region_id' => Region::where('libelle', 'Est')->first()->uuid],
            ['libelle' => 'Houet', 'region_id' => Region::where('libelle', 'Hauts-Bassins')->first()->uuid],
            ['libelle' => 'Kenedougou', 'region_id' => Region::where('libelle', 'Hauts-Bassins')->first()->uuid],
            ['libelle' => 'Tuy', 'region_id' => Region::where('libelle', 'Hauts-Bassins')->first()->uuid],
            ['libelle' => 'Loroum', 'region_id' => Region::where('libelle', 'Nord')->first()->uuid],
            ['libelle' => 'Passoré', 'region_id' => Region::where('libelle', 'Nord')->first()->uuid],
            ['libelle' => 'Yatenga', 'region_id' => Region::where('libelle', 'Nord')->first()->uuid],
            ['libelle' => 'Zondoma', 'region_id' => Region::where('libelle', 'Nord')->first()->uuid],
            ['libelle' => 'Ganzourgou', 'region_id' => Region::where('libelle', 'Plateau-Central')->first()->uuid],
            ['libelle' => 'Kourwéogo', 'region_id' => Region::where('libelle', 'Plateau-Central')->first()->uuid],
            ['libelle' => 'Oubritenga', 'region_id' => Region::where('libelle', 'Plateau-Central')->first()->uuid],
            ['libelle' => 'Oudalan', 'region_id' => Region::where('libelle', 'Sahel')->first()->uuid],
            ['libelle' => 'Séno', 'region_id' => Region::where('libelle', 'Sahel')->first()->uuid],
            ['libelle' => 'Soum', 'region_id' => Region::where('libelle', 'Sahel')->first()->uuid],
            ['libelle' => 'Yagha', 'region_id' => Region::where('libelle', 'Sahel')->first()->uuid],
            ['libelle' => 'Bougouriba', 'region_id' => Region::where('libelle', 'Sud-Ouest')->first()->uuid],
            ['libelle' => 'Ioba', 'region_id' => Region::where('libelle', 'Sud-Ouest')->first()->uuid],
            ['libelle' => 'Noumbiel', 'region_id' => Region::where('libelle', 'Sud-Ouest')->first()->uuid],
            ['libelle' => 'Poni', 'region_id' => Region::where('libelle', 'Sud-Ouest')->first()->uuid],
        ];

        foreach ($provinces as $key => $province) {
            Province::create([
                'libelle' => $province['libelle'],
                'region_id' => $province['region_id'],
            ]);
        }

        $communes = [
            ['libelle' => 'Bagassi', 'province_id' => Province::where('libelle', 'Balé')->first()->uuid, 'statut'=>false],
            ['libelle' => 'Bana', 'province_id' => Province::where('libelle', 'Balé')->first()->uuid, 'statut'=>false],
            ['libelle' => 'Boromo', 'province_id' => Province::where('libelle', 'Balé')->first()->uuid, 'statut'=>false],
            ['libelle' => 'Fara', 'province_id' => Province::where('libelle', 'Balé')->first()->uuid, 'statut'=>false],
            ['libelle' => 'Oury', 'province_id' => Province::where('libelle', 'Balé')->first()->uuid, 'statut'=>false],
            ['libelle' => 'Pa', 'province_id' => Province::where('libelle', 'Balé')->first()->uuid, 'statut'=>false],
            ['libelle' => 'Pompoi', 'province_id' => Province::where('libelle', 'Balé')->first()->uuid, 'statut'=>false],
            ['libelle' => 'Poura', 'province_id' => Province::where('libelle', 'Balé')->first()->uuid, 'statut'=>false],
            ['libelle' => 'Siby', 'province_id' => Province::where('libelle', 'Balé')->first()->uuid, 'statut'=>false],
            ['libelle' => 'Yaho', 'province_id' => Province::where('libelle', 'Balé')->first()->uuid, 'statut'=>false],

            ['libelle' => 'Balave', 'province_id' => Province::where('libelle', 'Banwa')->first()->uuid, 'statut'=>false],
            ['libelle' => 'Kouka', 'province_id' => Province::where('libelle', 'Banwa')->first()->uuid, 'statut'=>false],
            ['libelle' => 'Sami', 'province_id' => Province::where('libelle', 'Banwa')->first()->uuid, 'statut'=>false],
            ['libelle' => 'Sanaba', 'province_id' => Province::where('libelle', 'Banwa')->first()->uuid, 'statut'=>false],
            ['libelle' => 'Solenzo', 'province_id' => Province::where('libelle', 'Banwa')->first()->uuid, 'statut'=>false],
            ['libelle' => 'Tansila', 'province_id' => Province::where('libelle', 'Banwa')->first()->uuid, 'statut'=>false],

            ['libelle' => 'Barani', 'province_id' => Province::where('libelle', 'Kossi')->first()->uuid, 'statut'=>false],
            ['libelle' => 'Bomborokuy', 'province_id' => Province::where('libelle', 'Kossi')->first()->uuid, 'statut'=>false],
            ['libelle' => 'Bourasso', 'province_id' => Province::where('libelle', 'Kossi')->first()->uuid, 'statut'=>false],
            ['libelle' => 'Djibasso', 'province_id' => Province::where('libelle', 'Kossi')->first()->uuid, 'statut'=>false],
            ['libelle' => 'Dokuy', 'province_id' => Province::where('libelle', 'Kossi')->first()->uuid, 'statut'=>false],
            ['libelle' => 'Doumbala', 'province_id' => Province::where('libelle', 'Kossi')->first()->uuid, 'statut'=>false],
            ['libelle' => 'Kombori', 'province_id' => Province::where('libelle', 'Kossi')->first()->uuid, 'statut'=>false],
            ['libelle' => 'Madouba', 'province_id' => Province::where('libelle', 'Kossi')->first()->uuid, 'statut'=>false],
            ['libelle' => 'Nouna', 'province_id' => Province::where('libelle', 'Kossi')->first()->uuid, 'statut'=>false],
            ['libelle' => 'Sono', 'province_id' => Province::where('libelle', 'Kossi')->first()->uuid, 'statut'=>false],

            ['libelle' => 'Bondoukuy', 'province_id' => Province::where('libelle', 'Mouhoun')->first()->uuid, 'statut'=>false],
            ['libelle' => 'Dedougou', 'province_id' => Province::where('libelle', 'Mouhoun')->first()->uuid, 'statut'=>false],
            ['libelle' => 'Douroula', 'province_id' => Province::where('libelle', 'Mouhoun')->first()->uuid, 'statut'=>false],
            ['libelle' => 'Kona', 'province_id' => Province::where('libelle', 'Mouhoun')->first()->uuid, 'statut'=>false],
            ['libelle' => 'Ouarkoye', 'province_id' => Province::where('libelle', 'Mouhoun')->first()->uuid, 'statut'=>false],
            ['libelle' => 'Safane', 'province_id' => Province::where('libelle', 'Mouhoun')->first()->uuid, 'statut'=>false],
            ['libelle' => 'Tcheriba', 'province_id' => Province::where('libelle', 'Mouhoun')->first()->uuid, 'statut'=>false],

            ['libelle' => 'Gassan', 'province_id' => Province::where('libelle', 'Nayala')->first()->uuid, 'statut'=>false],
            ['libelle' => 'Gossina', 'province_id' => Province::where('libelle', 'Nayala')->first()->uuid, 'statut'=>false],
            ['libelle' => 'Kougny', 'province_id' => Province::where('libelle', 'Nayala')->first()->uuid, 'statut'=>false],
            ['libelle' => 'Toma', 'province_id' => Province::where('libelle', 'Nayala')->first()->uuid, 'statut'=>false],
            ['libelle' => 'Yaba', 'province_id' => Province::where('libelle', 'Nayala')->first()->uuid, 'statut'=>false],
            ['libelle' => 'Ye', 'province_id' => Province::where('libelle', 'Nayala')->first()->uuid, 'statut'=>false],

            ['libelle' => 'Di', 'province_id' => Province::where('libelle', 'Sourou')->first()->uuid, 'statut'=>false],
            ['libelle' => 'Gomboro', 'province_id' => Province::where('libelle', 'Sourou')->first()->uuid, 'statut'=>false],
            ['libelle' => 'Kassoum', 'province_id' => Province::where('libelle', 'Sourou')->first()->uuid, 'statut'=>false],
            ['libelle' => 'Kiembara', 'province_id' => Province::where('libelle', 'Sourou')->first()->uuid, 'statut'=>false],
            ['libelle' => 'Lanfiera', 'province_id' => Province::where('libelle', 'Sourou')->first()->uuid, 'statut'=>false],
            ['libelle' => 'Lankoue', 'province_id' => Province::where('libelle', 'Sourou')->first()->uuid, 'statut'=>false],
            ['libelle' => 'Toeni', 'province_id' => Province::where('libelle', 'Sourou')->first()->uuid, 'statut'=>false],
            ['libelle' => 'Tougan', 'province_id' => Province::where('libelle', 'Sourou')->first()->uuid, 'statut'=>false],

            ['libelle' => 'Banfora', 'province_id' => Province::where('libelle', 'Comoé')->first()->uuid, 'statut'=>false],
            ['libelle' => 'Beregadougou', 'province_id' => Province::where('libelle', 'Comoé')->first()->uuid, 'statut'=>false],
            ['libelle' => 'Mangodara', 'province_id' => Province::where('libelle', 'Comoé')->first()->uuid, 'statut'=>false],
            ['libelle' => 'Moussodougou', 'province_id' => Province::where('libelle', 'Comoé')->first()->uuid, 'statut'=>false],
            ['libelle' => 'Niangoloko', 'province_id' => Province::where('libelle', 'Comoé')->first()->uuid, 'statut'=>false],
            ['libelle' => 'Ouo', 'province_id' => Province::where('libelle', 'Comoé')->first()->uuid, 'statut'=>false],
            ['libelle' => 'Sideradougou', 'province_id' => Province::where('libelle', 'Comoé')->first()->uuid, 'statut'=>false],
            ['libelle' => 'Soubakaniedougou', 'province_id' => Province::where('libelle', 'Comoé')->first()->uuid, 'statut'=>false],
            ['libelle' => 'Tiefora', 'province_id' => Province::where('libelle', 'Comoé')->first()->uuid, 'statut'=>false],

            ['libelle' => 'Dakoro', 'province_id' => Province::where('libelle', 'Léraba')->first()->uuid, 'statut'=>false],
            ['libelle' => 'Douna', 'province_id' => Province::where('libelle', 'Léraba')->first()->uuid, 'statut'=>false],
            ['libelle' => 'Kankalaba', 'province_id' => Province::where('libelle', 'Léraba')->first()->uuid, 'statut'=>false],
            ['libelle' => 'Loumana', 'province_id' => Province::where('libelle', 'Léraba')->first()->uuid, 'statut'=>false],
            ['libelle' => 'Niankorodougou', 'province_id' => Province::where('libelle', 'Léraba')->first()->uuid, 'statut'=>false],
            ['libelle' => 'Oueleni', 'province_id' => Province::where('libelle', 'Léraba')->first()->uuid, 'statut'=>false],
            ['libelle' => 'Sindou', 'province_id' => Province::where('libelle', 'Léraba')->first()->uuid, 'statut'=>false],
            ['libelle' => 'Wolokonto', 'province_id' => Province::where('libelle', 'Léraba')->first()->uuid, 'statut'=>false],

            ['libelle' => 'Komki-ipala', 'province_id' => Province::where('libelle', 'Kadiogo')->first()->uuid, 'statut'=>false],
            ['libelle' => 'Komsilga', 'province_id' => Province::where('libelle', 'Kadiogo')->first()->uuid, 'statut'=>false],
            ['libelle' => 'Koubri', 'province_id' => Province::where('libelle', 'Kadiogo')->first()->uuid, 'statut'=>false],
            ['libelle' => 'Pabre', 'province_id' => Province::where('libelle', 'Kadiogo')->first()->uuid, 'statut'=>false],
            ['libelle' => 'Saaba', 'province_id' => Province::where('libelle', 'Kadiogo')->first()->uuid, 'statut'=>false],
            ['libelle' => 'Tanghin-dassouri', 'province_id' => Province::where('libelle', 'Kadiogo')->first()->uuid, 'statut'=>false],
            ['libelle' => 'Ouagadougou', 'province_id' => Province::where('libelle', 'Kadiogo')->first()->uuid, 'statut'=>true],

            ['libelle' => 'Bagre', 'province_id' => Province::where('libelle', 'Boulgou')->first()->uuid, 'statut'=>false],
            ['libelle' => 'Bane', 'province_id' => Province::where('libelle', 'Boulgou')->first()->uuid, 'statut'=>false],
            ['libelle' => 'Beguedo', 'province_id' => Province::where('libelle', 'Boulgou')->first()->uuid, 'statut'=>false],
            ['libelle' => 'Bissiga', 'province_id' => Province::where('libelle', 'Boulgou')->first()->uuid, 'statut'=>false],
            ['libelle' => 'Bittou', 'province_id' => Province::where('libelle', 'Boulgou')->first()->uuid, 'statut'=>false],
            ['libelle' => 'Boussouma', 'province_id' => Province::where('libelle', 'Boulgou')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Garango', 'province_id' => Province::where('libelle', 'Boulgou')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Komtoega', 'province_id' => Province::where('libelle', 'Boulgou')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Niaogho', 'province_id' => Province::where('libelle', 'Boulgou')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Tenkodogo', 'province_id' => Province::where('libelle', 'Boulgou')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Zabre', 'province_id' => Province::where('libelle', 'Boulgou')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Zoaga', 'province_id' => Province::where('libelle', 'Boulgou')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Zonse', 'province_id' => Province::where('libelle', 'Boulgou')->first()->uuid, 'statut'=>false],

            ['libelle' =>   'Comin-yanga', 'province_id' => Province::where('libelle', 'Koulpélogo')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Dourtenga', 'province_id' => Province::where('libelle', 'Koulpélogo')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Lalgaye', 'province_id' => Province::where('libelle', 'Koulpélogo')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Ouargaye', 'province_id' => Province::where('libelle', 'Koulpélogo')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Sangha', 'province_id' => Province::where('libelle', 'Koulpélogo')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Soudougui', 'province_id' => Province::where('libelle', 'Koulpélogo')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Yargatenga', 'province_id' => Province::where('libelle', 'Koulpélogo')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Yonde', 'province_id' => Province::where('libelle', 'Koulpélogo')->first()->uuid, 'statut'=>false],

            ['libelle' =>   'Andemtenga', 'province_id' => Province::where('libelle', 'Kouritenga')->first()->uuid, 'statut'=>false],
            ['libelle' =>    'Baskoure', 'province_id' => Province::where('libelle', 'Kouritenga')->first()->uuid, 'statut'=>false],
            ['libelle' =>    'Dialgaye', 'province_id' => Province::where('libelle', 'Kouritenga')->first()->uuid, 'statut'=>false],
            ['libelle' =>    'Gounghin', 'province_id' => Province::where('libelle', 'Kouritenga')->first()->uuid, 'statut'=>false],
            ['libelle' =>    'Kando', 'province_id' => Province::where('libelle', 'Kouritenga')->first()->uuid, 'statut'=>false],
            ['libelle' =>    'Koupela', 'province_id' => Province::where('libelle', 'Kouritenga')->first()->uuid, 'statut'=>false],
            ['libelle' =>  'Pouytenga', 'province_id' => Province::where('libelle', 'Kouritenga')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Tensobentenga', 'province_id' => Province::where('libelle', 'Kouritenga')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Yargo', 'province_id' => Province::where('libelle', 'Kouritenga')->first()->uuid, 'statut'=>false],

            ['libelle' =>   'Bourzanga', 'province_id' => Province::where('libelle', 'Bam')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Guibare', 'province_id' => Province::where('libelle', 'Bam')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Kongoussi', 'province_id' => Province::where('libelle', 'Bam')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Nassere', 'province_id' => Province::where('libelle', 'Bam')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Rollo', 'province_id' => Province::where('libelle', 'Bam')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Rouko', 'province_id' => Province::where('libelle', 'Bam')->first()->uuid, 'statut'=>false],
            ['libelle' =>    'Sabce', 'province_id' => Province::where('libelle', 'Bam')->first()->uuid, 'statut'=>false],
            ['libelle' =>    'Tikare', 'province_id' => Province::where('libelle', 'Bam')->first()->uuid, 'statut'=>false],
            ['libelle' =>    'Zimtanga', 'province_id' => Province::where('libelle', 'Bam')->first()->uuid, 'statut'=>false],

            ['libelle' =>   'Boala', 'province_id' => Province::where('libelle', 'Namentenga')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Boulsa', 'province_id' => Province::where('libelle', 'Namentenga')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Bouroum', 'province_id' => Province::where('libelle', 'Namentenga')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Dargo', 'province_id' => Province::where('libelle', 'Namentenga')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Nagbingou', 'province_id' => Province::where('libelle', 'Namentenga')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Tougouri', 'province_id' => Province::where('libelle', 'Namentenga')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Yalgo', 'province_id' => Province::where('libelle', 'Namentenga')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Zeguedeguin', 'province_id' => Province::where('libelle', 'Namentenga')->first()->uuid, 'statut'=>false],

            ['libelle' =>   'Barsalogho', 'province_id' => Province::where('libelle', 'Sanmatenga')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Boussoumah', 'province_id' => Province::where('libelle', 'Sanmatenga')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Dablo', 'province_id' => Province::where('libelle', 'Sanmatenga')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Kaya', 'province_id' => Province::where('libelle', 'Sanmatenga')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Korsimoro', 'province_id' => Province::where('libelle', 'Sanmatenga')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Mane', 'province_id' => Province::where('libelle', 'Sanmatenga')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Namissiguimah', 'province_id' => Province::where('libelle', 'Sanmatenga')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Pensa', 'province_id' => Province::where('libelle', 'Sanmatenga')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Pibaore', 'province_id' => Province::where('libelle', 'Sanmatenga')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Pissila', 'province_id' => Province::where('libelle', 'Sanmatenga')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Ziga', 'province_id' => Province::where('libelle', 'Sanmatenga')->first()->uuid, 'statut'=>false],

            ['libelle' =>   'Bingo', 'province_id' => Province::where('libelle', 'Boulkiemdé')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Imasgo', 'province_id' => Province::where('libelle', 'Boulkiemdé')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Kindi', 'province_id' => Province::where('libelle', 'Boulkiemdé')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Kokologho', 'province_id' => Province::where('libelle', 'Boulkiemdé')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Koudougou', 'province_id' => Province::where('libelle', 'Boulkiemdé')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Nandiala', 'province_id' => Province::where('libelle', 'Boulkiemdé')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Nanoro', 'province_id' => Province::where('libelle', 'Boulkiemdé')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Pella', 'province_id' => Province::where('libelle', 'Boulkiemdé')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Poa', 'province_id' => Province::where('libelle', 'Boulkiemdé')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Ramongo', 'province_id' => Province::where('libelle', 'Boulkiemdé')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Sabou', 'province_id' => Province::where('libelle', 'Boulkiemdé')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Sigle', 'province_id' => Province::where('libelle', 'Boulkiemdé')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Soaw', 'province_id' => Province::where('libelle', 'Boulkiemdé')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Sourgou', 'province_id' => Province::where('libelle', 'Boulkiemdé')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Thyou', 'province_id' => Province::where('libelle', 'Boulkiemdé')->first()->uuid, 'statut'=>false],

            ['libelle' =>   'Dassa', 'province_id' => Province::where('libelle', 'Sanguié')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Didyr', 'province_id' => Province::where('libelle', 'Sanguié')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Godyr', 'province_id' => Province::where('libelle', 'Sanguié')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Kordie', 'province_id' => Province::where('libelle', 'Sanguié')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Kyon', 'province_id' => Province::where('libelle', 'Sanguié')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Pouni', 'province_id' => Province::where('libelle', 'Sanguié')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Reo', 'province_id' => Province::where('libelle', 'Sanguié')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Tenado', 'province_id' => Province::where('libelle', 'Sanguié')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Zamo', 'province_id' => Province::where('libelle', 'Sanguié')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Zawara', 'province_id' => Province::where('libelle', 'Sanguié')->first()->uuid, 'statut'=>false],

            ['libelle' =>   'Bieha', 'province_id' => Province::where('libelle', 'Sissili')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Boura', 'province_id' => Province::where('libelle', 'Sissili')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Leo', 'province_id' => Province::where('libelle', 'Sissili')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Nebielianayou', 'province_id' => Province::where('libelle', 'Sissili')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Niabouri', 'province_id' => Province::where('libelle', 'Sissili')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Silly', 'province_id' => Province::where('libelle', 'Sissili')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'To', 'province_id' => Province::where('libelle', 'Sissili')->first()->uuid, 'statut'=>false],

            ['libelle' =>   'Bakata', 'province_id' => Province::where('libelle', 'Ziro')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Bougnounou', 'province_id' => Province::where('libelle', 'Ziro')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Cassou', 'province_id' => Province::where('libelle', 'Ziro')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Dalo', 'province_id' => Province::where('libelle', 'Ziro')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Gao', 'province_id' => Province::where('libelle', 'Ziro')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Sapouy', 'province_id' => Province::where('libelle', 'Ziro')->first()->uuid, 'statut'=>false],

            ['libelle' =>   'Doulougou', 'province_id' => Province::where('libelle', 'Bazèga')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Gaongo', 'province_id' => Province::where('libelle', 'Bazèga')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Ipelce', 'province_id' => Province::where('libelle', 'Bazèga')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Kayao', 'province_id' => Province::where('libelle', 'Bazèga')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Kombissiri', 'province_id' => Province::where('libelle', 'Bazèga')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Sapone', 'province_id' => Province::where('libelle', 'Bazèga')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Toece', 'province_id' => Province::where('libelle', 'Bazèga')->first()->uuid, 'statut'=>false],

            ['libelle' =>   'Guiaro', 'province_id' => Province::where('libelle', 'Nahouri')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Po', 'province_id' => Province::where('libelle', 'Nahouri')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Tiebele', 'province_id' => Province::where('libelle', 'Nahouri')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Zecco', 'province_id' => Province::where('libelle', 'Nahouri')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Ziou', 'province_id' => Province::where('libelle', 'Nahouri')->first()->uuid, 'statut'=>false],

            ['libelle' =>   'Bere', 'province_id' => Province::where('libelle', 'Zoundwéogo')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Binde', 'province_id' => Province::where('libelle', 'Zoundwéogo')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Gogo', 'province_id' => Province::where('libelle', 'Zoundwéogo')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Gonboussougou', 'province_id' => Province::where('libelle', 'Zoundwéogo')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Guiba', 'province_id' => Province::where('libelle', 'Zoundwéogo')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Manga', 'province_id' => Province::where('libelle', 'Zoundwéogo')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Nobere', 'province_id' => Province::where('libelle', 'Zoundwéogo')->first()->uuid, 'statut'=>false],

            ['libelle' =>   'Bilanga', 'province_id' => Province::where('libelle', 'Gnagna')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Bogande', 'province_id' => Province::where('libelle', 'Gnagna')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Coalla', 'province_id' => Province::where('libelle', 'Gnagna')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Liptougou', 'province_id' => Province::where('libelle', 'Gnagna')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Manni', 'province_id' => Province::where('libelle', 'Gnagna')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Piela', 'province_id' => Province::where('libelle', 'Gnagna')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Thion', 'province_id' => Province::where('libelle', 'Gnagna')->first()->uuid, 'statut'=>false],

            ['libelle' =>   'Diabo', 'province_id' => Province::where('libelle', 'Gourma')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Diapangou', 'province_id' => Province::where('libelle', 'Gourma')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Fada Ngourma', 'province_id' => Province::where('libelle', 'Gourma')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Matiacoali', 'province_id' => Province::where('libelle', 'Gourma')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Tibga', 'province_id' => Province::where('libelle', 'Gourma')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Yamba', 'province_id' => Province::where('libelle', 'Gourma')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Barthiebougou', 'province_id' => Province::where('libelle', 'Komondjari')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Foutouri', 'province_id' => Province::where('libelle', 'Komondjari')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Gayeri', 'province_id' => Province::where('libelle', 'Komondjari')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Kompienga', 'province_id' => Province::where('libelle', 'Kompienga')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Madjoari', 'province_id' => Province::where('libelle', 'Kompienga')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Pama', 'province_id' => Province::where('libelle', 'Kompienga')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Botou', 'province_id' => Province::where('libelle', 'Tapoa')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Diapaga', 'province_id' => Province::where('libelle', 'Tapoa')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Kantchari', 'province_id' => Province::where('libelle', 'Tapoa')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Logobou', 'province_id' => Province::where('libelle', 'Tapoa')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Namounou', 'province_id' => Province::where('libelle', 'Tapoa')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Partiaga', 'province_id' => Province::where('libelle', 'Tapoa')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Tambaga', 'province_id' => Province::where('libelle', 'Tapoa')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Tansarga', 'province_id' => Province::where('libelle', 'Tapoa')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Bama', 'province_id' => Province::where('libelle', 'Houet')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Dande', 'province_id' => Province::where('libelle', 'Houet')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Faramana', 'province_id' => Province::where('libelle', 'Houet')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Fo', 'province_id' => Province::where('libelle', 'Houet')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Karangasso sambla', 'province_id' => Province::where('libelle', 'Houet')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Karangasso-vigue', 'province_id' => Province::where('libelle', 'Houet')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Koundougou', 'province_id' => Province::where('libelle', 'Houet')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Lena', 'province_id' => Province::where('libelle', 'Houet')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Padema', 'province_id' => Province::where('libelle', 'Houet')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Peni', 'province_id' => Province::where('libelle', 'Houet')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Satiri', 'province_id' => Province::where('libelle', 'Houet')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Toussiana', 'province_id' => Province::where('libelle', 'Houet')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Bobo Dioulasso', 'province_id' => Province::where('libelle', 'Houet')->first()->uuid, 'statut'=>true],

            ['libelle' =>   'Banzon', 'province_id' => Province::where('libelle', 'Kénédougou')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Djigouera', 'province_id' => Province::where('libelle', 'Kénédougou')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Kangala', 'province_id' => Province::where('libelle', 'Kénédougou')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Kayan', 'province_id' => Province::where('libelle', 'Kénédougou')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Koloko', 'province_id' => Province::where('libelle', 'Kénédougou')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Kourinion', 'province_id' => Province::where('libelle', 'Kénédougou')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Kourouma', 'province_id' => Province::where('libelle', 'Kénédougou')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Morolaba', 'province_id' => Province::where('libelle', 'Kénédougou')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'N\'dorola', 'province_id' => Province::where('libelle', 'Kénédougou')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Orodara', 'province_id' => Province::where('libelle', 'Kénédougou')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Samogohiri', 'province_id' => Province::where('libelle', 'Kénédougou')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Samorogouan', 'province_id' => Province::where('libelle', 'Kénédougou')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Sindo', 'province_id' => Province::where('libelle', 'Kénédougou')->first()->uuid, 'statut'=>false],

            ['libelle' =>   'Bekuy', 'province_id' => Province::where('libelle', 'Tuy')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Bereba', 'province_id' => Province::where('libelle', 'Tuy')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Boni', 'province_id' => Province::where('libelle', 'Tuy')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Founzan', 'province_id' => Province::where('libelle', 'Tuy')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Hounde', 'province_id' => Province::where('libelle', 'Tuy')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Koti', 'province_id' => Province::where('libelle', 'Tuy')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Koumbia', 'province_id' => Province::where('libelle', 'Tuy')->first()->uuid, 'statut'=>false],

            ['libelle' =>   'Banh', 'province_id' => Province::where('libelle', 'Loroum')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Ouindigui', 'province_id' => Province::where('libelle', 'Loroum')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Solle', 'province_id' => Province::where('libelle', 'Loroum')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Titao', 'province_id' => Province::where('libelle', 'Loroum')->first()->uuid, 'statut'=>false],

            ['libelle' =>   'Arbolle', 'province_id' => Province::where('libelle', 'Passoré')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Bagare', 'province_id' => Province::where('libelle', 'Passoré')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Bokin', 'province_id' => Province::where('libelle', 'Passoré')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Gomponsom', 'province_id' => Province::where('libelle', 'Passoré')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Kirsi', 'province_id' => Province::where('libelle', 'Passoré')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'La-todin', 'province_id' => Province::where('libelle', 'Passoré')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Pilimpikou', 'province_id' => Province::where('libelle', 'Passoré')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Samba', 'province_id' => Province::where('libelle', 'Passoré')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Yako', 'province_id' => Province::where('libelle', 'Passoré')->first()->uuid, 'statut'=>false],

            ['libelle' =>   'Barga', 'province_id' => Province::where('libelle', 'Yatenga')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Kain', 'province_id' => Province::where('libelle', 'Yatenga')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Kalsaka', 'province_id' => Province::where('libelle', 'Yatenga')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Kossouka', 'province_id' => Province::where('libelle', 'Yatenga')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Koumbri', 'province_id' => Province::where('libelle', 'Yatenga')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Namissiguima', 'province_id' => Province::where('libelle', 'Yatenga')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Ouahigouya', 'province_id' => Province::where('libelle', 'Yatenga')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Oula', 'province_id' => Province::where('libelle', 'Yatenga')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Rambo', 'province_id' => Province::where('libelle', 'Yatenga')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Seguenega', 'province_id' => Province::where('libelle', 'Yatenga')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Tangaye', 'province_id' => Province::where('libelle', 'Yatenga')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Thiou', 'province_id' => Province::where('libelle', 'Yatenga')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Zogore', 'province_id' => Province::where('libelle', 'Yatenga')->first()->uuid, 'statut'=>false],

            ['libelle' =>   'Bassi', 'province_id' => Province::where('libelle', 'Zondoma')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Boussou', 'province_id' => Province::where('libelle', 'Zondoma')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Gourcy', 'province_id' => Province::where('libelle', 'Zondoma')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Leba', 'province_id' => Province::where('libelle', 'Zondoma')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Tougo', 'province_id' => Province::where('libelle', 'Zondoma')->first()->uuid, 'statut'=>false],

            ['libelle' =>   'Boudry', 'province_id' => Province::where('libelle', 'Ganzourgou')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Kogho', 'province_id' => Province::where('libelle', 'Ganzourgou')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Meguet', 'province_id' => Province::where('libelle', 'Ganzourgou')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Mogtedo', 'province_id' => Province::where('libelle', 'Ganzourgou')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Salogo', 'province_id' => Province::where('libelle', 'Ganzourgou')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Zam', 'province_id' => Province::where('libelle', 'Ganzourgou')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Zorgho', 'province_id' => Province::where('libelle', 'Ganzourgou')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Zoungou', 'province_id' => Province::where('libelle', 'Ganzourgou')->first()->uuid, 'statut'=>false],

            ['libelle' =>   'Bousse', 'province_id' => Province::where('libelle', 'Kourwéogo')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Laye', 'province_id' => Province::where('libelle', 'Kourwéogo')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Niou', 'province_id' => Province::where('libelle', 'Kourwéogo')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Sourgoubila', 'province_id' => Province::where('libelle', 'Kourwéogo')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Toeghin', 'province_id' => Province::where('libelle', 'Kourwéogo')->first()->uuid, 'statut'=>false],

            ['libelle' =>   'Absouya', 'province_id' => Province::where('libelle', 'Oubritenga')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Dapelogo', 'province_id' => Province::where('libelle', 'Oubritenga')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Loumbila', 'province_id' => Province::where('libelle', 'Oubritenga')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Nagreongo', 'province_id' => Province::where('libelle', 'Oubritenga')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Ourgou-manega', 'province_id' => Province::where('libelle', 'Oubritenga')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Ziniare', 'province_id' => Province::where('libelle', 'Oubritenga')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Zitenga', 'province_id' => Province::where('libelle', 'Oubritenga')->first()->uuid, 'statut'=>false],

            ['libelle' =>   'Deou', 'province_id' => Province::where('libelle', 'Oudalan')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Gorom-gorom', 'province_id' => Province::where('libelle', 'Oudalan')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Markoye', 'province_id' => Province::where('libelle', 'Oudalan')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Oursi', 'province_id' => Province::where('libelle', 'Oudalan')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Tin-akoff', 'province_id' => Province::where('libelle', 'Oudalan')->first()->uuid, 'statut'=>false],

            ['libelle' =>   'Bani', 'province_id' => Province::where('libelle', 'Séno')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Dori', 'province_id' => Province::where('libelle', 'Séno')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Falagountou', 'province_id' => Province::where('libelle', 'Séno')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Gorgadji', 'province_id' => Province::where('libelle', 'Séno')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Sampelga', 'province_id' => Province::where('libelle', 'Séno')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Seytenga', 'province_id' => Province::where('libelle', 'Séno')->first()->uuid, 'statut'=>false],

            ['libelle' =>   'Arbinda', 'province_id' => Province::where('libelle', 'Soum')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Baraboule', 'province_id' => Province::where('libelle', 'Soum')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Diguel', 'province_id' => Province::where('libelle', 'Soum')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Djibo', 'province_id' => Province::where('libelle', 'Soum')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Kelbo', 'province_id' => Province::where('libelle', 'Soum')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Koutougou', 'province_id' => Province::where('libelle', 'Soum')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Nassoumbou', 'province_id' => Province::where('libelle', 'Soum')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Pobe-mengao', 'province_id' => Province::where('libelle', 'Soum')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Tongomayel', 'province_id' => Province::where('libelle', 'Soum')->first()->uuid, 'statut'=>false],

            ['libelle' =>   'Boundore', 'province_id' => Province::where('libelle', 'Yagha')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Mansila', 'province_id' => Province::where('libelle', 'Yagha')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Sebba', 'province_id' => Province::where('libelle', 'Yagha')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Solhan', 'province_id' => Province::where('libelle', 'Yagha')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Tankougounadie', 'province_id' => Province::where('libelle', 'Yagha')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Titabe', 'province_id' => Province::where('libelle', 'Yagha')->first()->uuid, 'statut'=>false],

            ['libelle' =>   'Bondigui', 'province_id' => Province::where('libelle', 'Bougouriba')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Diebougou', 'province_id' => Province::where('libelle', 'Bougouriba')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Dolo', 'province_id' => Province::where('libelle', 'Bougouriba')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Iolonioro', 'province_id' => Province::where('libelle', 'Bougouriba')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Tiankoura', 'province_id' => Province::where('libelle', 'Bougouriba')->first()->uuid, 'statut'=>false],

            ['libelle' =>   'Dano', 'province_id' => Province::where('libelle', 'Ioba')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Dissin', 'province_id' => Province::where('libelle', 'Ioba')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Gueguere', 'province_id' => Province::where('libelle', 'Ioba')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Koper', 'province_id' => Province::where('libelle', 'Ioba')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Niego', 'province_id' => Province::where('libelle', 'Ioba')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Oronkua', 'province_id' => Province::where('libelle', 'Ioba')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Ouessa', 'province_id' => Province::where('libelle', 'Ioba')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Zambo', 'province_id' => Province::where('libelle', 'Ioba')->first()->uuid, 'statut'=>false],

            ['libelle' =>   'Batie', 'province_id' => Province::where('libelle', 'Noumbiel')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Boussoukoula', 'province_id' => Province::where('libelle', 'Noumbiel')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Kpuere', 'province_id' => Province::where('libelle', 'Noumbiel')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Legmoin', 'province_id' => Province::where('libelle', 'Noumbiel')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Midebdo', 'province_id' => Province::where('libelle', 'Noumbiel')->first()->uuid, 'statut'=>false],

            ['libelle' =>   'Bouroum-bouroum', 'province_id' => Province::where('libelle', 'Poni')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Boussera', 'province_id' => Province::where('libelle', 'Poni')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Djigoue', 'province_id' => Province::where('libelle', 'Poni')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Gaoua', 'province_id' => Province::where('libelle', 'Poni')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Gbomblora', 'province_id' => Province::where('libelle', 'Poni')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Kampti', 'province_id' => Province::where('libelle', 'Poni')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Loropeni', 'province_id' => Province::where('libelle', 'Poni')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Malba', 'province_id' => Province::where('libelle', 'Poni')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Nako', 'province_id' => Province::where('libelle', 'Poni')->first()->uuid, 'statut'=>false],
            ['libelle' =>   'Perigban', 'province_id' => Province::where('libelle', 'Poni')->first()->uuid, 'statut'=>false],
        ];

        foreach ($communes as $key => $commune) {
            Commune::create([
                'libelle' => $commune['libelle'],
                'province_id' => $commune['province_id'],
                'statut' => $commune['statut'],
            ]);
        }
    }
}
